project: 
  type: website
  output-dir: docs

website: 
  title: Real-Time Analytics
  navbar:
    left: 
          - href: index.qmd
            text: Home
          - href: wyklad1.qmd
            text: Lecture 1
          - href: sylabus.qmd
            text: Sylabus
          - href: info.qmd
            text: Tools
          - href: ksiazki.qmd
            text: Books
          

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    self-contained-math: true