---
title: "Informacje ogólne"
---

## Analiza danych w czasie rzeczywistym

Kod: 222890-D

Semestr zimowy 2022/2023,
SGH Szkoła Główna Handlowa w Warszawie

Podstawowe informacje znajdziesz w [sylabusie](/RTA_2023/sylabus).

Ciekawe książki i strony internetowe zamieszczone zostały w zakładce [książki](/RTA_2023/ksiazki). Jeśli chciał(a)byś coś dodać prześlij informację przez MS teams.

## Kalendarz

#### Wykład 

Wykład jest realizowany w trybie hybrydowym.
Jest on NIEOBOWIĄZKOWY i odbywa się w Auli I bud G

1. 20-02-2023 (poniedziałek) 09:50-11:30 - Wykład 1
2. 27-02-2023 (poniedziałek) 09:50-11:30 - Wykład 2
3. 06-03-2023 (poniedziałek) 09:50-11:30 - Wykład 3
4. 13-03-2023 (poniedziałek) 09:50-11:30 - Wykład 4

Wykłady kończą się TESTEM: 10 pytań - 20 minut. 
Test przeprowadzany jest za pośrednictwem MS Teams.

#### Laboratoria

1. 20-03-2023 (poniedziałek) 08:00-13:30 - C4D 3 grupy
1. 21-03-2023 (wtorek) 11:40-17:00 - C4D 3 grupy

2. 27-03-2023 (poniedziałek) 08:00-13:30 - C4D, 3 grupy
2. 28-03-2023 (wtorek) 11:40-17:00 - C4D, 3 grupy

3. 03-04-2023 (poniedziałek) 08:00-13:30 - C4D, 3 grupy
3. 04-04-2023 (wtorek) 11:40-17:00 - C4D, 3 grupy 

4. 17-04-2023 (poniedziałek) 08:00-13:30 - C4D, 3 grupy
4. 18-04-2023 (wtorek) 11:40-17:00 - C4D, 3 grupy 

5. 24-04-2023 (poniedziałek) 08:00-13:30 - C4D, 3 grupy
5. 25-04-2023 (wtorek) 11:40-17:00 - C4D, 3 grupy 

6. 08-05-2023 (poniedziałek) 08:00-13:30 - C4D, 3 grupy
6. 09-05-2023 (wtorek) 11:40-17:00 - C4D, 3 grupy 

7. 15-05-2023 (poniedziałek) 08:00-13:30 - C4D, 3 grupy
7. 16-05-2023 (wtorek) 11:40-17:00 - C4D, 3 grupy 

8. 22-05-2023 (poniedziałek) 08:00-13:30 - C4D, 3 grupy
8. 23-05-2023 (wtorek) 11:40-17:00 - C4D, 3 grupy 

9. 29-05-2023 (poniedziałek) 08:00-13:30 - C4D, 3 grupy
9. 30-05-2023 (wtorek) 11:40-17:00 - C4D, 3 grupy

10. 05-06-2023 (poniedziałek) 08:00-13:30 - C4D, 3 grupy
10. 06-06-2023 (wtorek) 11:40-17:00 - C4D, 3 grupy 

#### Miejsce

Wykłady 1-5: G-Aula I
Laboratorium 1-9: C-4D

#### Zaliczenie i Egzamin

Wykłady zakończone zostaną testem (ostatnie zajęcia).
Pozytywna ocena z testu (powyżej 13 pkt) upoważnia do realizacji ćwiczeń. 

Po ćwiczeniach realizowane będą zadania domowe przekazywane za pośrednictwem platformy teams.  
Zaliczenie wszystkich ćwiczeń i zadań upoważnia do realizacji projektu. 

Projekt powinien być realizowany w grupach max 5 osobowych. 

Wymagania projektu: 

- Projekt powinien przedstawiać BIZNESOWY PROBLEM, który można realizować wykorzystując informacje podawane w trybie online. (Nie oznacza to, że nie można korzystać z procesowania batchowego np w celu wygenerowania modelu).
- Dane powinny być przesyłane do Apache Kafki i stamtąd poddawane dalszemu procesowaniu i analizie. 
- Język programowania jest dowolny - dotyczy każdego komponentu projektu. 
- Można wykorzystać narzędzia BI 
- Źródłem danych może być tabela, sztucznie generowane dane, IoT itp.

## Technologie

Uczestnicząc w zajęciach musisz opanować i przynajmniej w podstawowym zakresie posługiwać się następującymi technologiami informatycznymi:

1. [GIT](https://sebkaz-teaching.github.io/RTA_2023/info/) 
2. Python, Jupyter notebook, Jupyter lab, Colab
3. [Docker](https://sebkaz-teaching.github.io/RTA_2023/info/)
4. **Apache Spark**, Apache Flink, **Apache Kafka**, Apache Beam
5. Databricks Community edition [Web page](https://community.cloud.databricks.com/login.html).